import assert from 'node:assert/strict';
import fs from 'node:fs';

const read = (path: string) => fs.readFileSync(new URL(path, import.meta.url), 'utf8');

const createRoute = read('../src/pages/api/projects/[id]/automation-jobs.ts');
const claimRoute = read('../src/pages/api/desktop/automation-jobs/[id]/claim.ts');
const documentRoute = read('../src/pages/api/desktop/documents/[id].ts');
const launcher = read('../src/components/automation/AutomationLaunchButton.tsx');
const tokenAuth = read('../src/server/auth/desktop-token.ts');
const exchangeRoute = read('../src/pages/api/desktop/handoff/exchange.ts');
const relaunchRoute = read('../src/pages/api/automation-jobs/[id]/launch.ts');
const desktopIntegration = read('../src/components/integrations/DesktopAccessIntegration.tsx');
const automationJobService = read('../src/server/services/automation-jobs.service.ts');
const desktopCallbackRoute = read('../src/pages/api/desktop/automation-jobs/[id]/index.ts');
const lifecycleService = read('../src/server/services/automation-lifecycle.service.ts');

assert.match(createRoute, /requireProjectAccess\(organisation\.id, projectId\)/, 'job creation must verify project access');
assert.match(createRoute, /AutomationJobStatus\.PREFLIGHT_REQUIRED/, 'new portal jobs require review before desktop launch');
assert.match(createRoute, /AutomationJobStatus\.NEEDS_INPUT/, 'incomplete portal jobs remain in needs-input state');
assert.match(createRoute, /redirectTo:\s*`\/automation-job\/\$\{job\.id\}`/, 'new portal jobs open the prepared review page');
assert.match(claimRoute, /claimedDeviceId:\s*access\.id/, 'claims must bind the job to the authenticated desktop token');
assert.match(claimRoute, /already open on another desktop device/, 'duplicate claims must be rejected clearly');
assert.match(documentRoute, /organisationId:\s*access\.organisationId/, 'document downloads must be organisation scoped');
assert.match(documentRoute, /documentSnapshot/, 'downloads must be restricted to documents frozen into the job');
assert.doesNotMatch(launcher, /password|storageKey/i, 'custom protocol launch must not include portal passwords or storage keys');
assert.doesNotMatch(createRoute, /buildDesktopLaunchUrl|createDesktopHandoffCode/, 'job preparation must not issue a desktop handoff before review');
assert.match(tokenAuth, /Buffer\.from\(portalOrigin, 'utf8'\)\.toString\('base64url'\)/, 'launch data uses path-safe encoding instead of a query string');
assert.doesNotMatch(tokenAuth, /new URLSearchParams/, 'custom protocol launches must not depend on query strings that Windows may drop');
assert.match(tokenAuth, /process\.env\.PUBLIC_SITE_URL/, 'desktop links must prefer the configured public portal origin');
assert.match(tokenAuth, /PUBLIC_SITE_URL in production/, 'production must reject accidental localhost handoff origins');
assert.match(relaunchRoute, /desktopPortalOrigin\(context\.request\)/, 'relaunches must encode the trusted public portal origin');
assert.doesNotMatch(relaunchRoute, /context\.url\.origin/, 'relaunch links must not use an internal platform request origin');
assert.match(relaunchRoute, /requireOrganisation\(context\)/, 'relaunching an existing job requires an organisation session');
assert.match(relaunchRoute, /organisationId:\s*organisation\.id/, 'existing job relaunch is organisation scoped');
assert.match(exchangeRoute, /handoffRedeemedAt:\s*null/, 'handoff exchange only accepts unused links');
assert.match(exchangeRoute, /handoffExpiresAt:\s*\{ gt: now \}/, 'handoff exchange rejects expired links');
assert.match(exchangeRoute, /automationJobId:\s*job\.id/, 'automatic desktop credentials are scoped to one job');
assert.match(exchangeRoute, /handoffCodeHash:\s*null/, 'redeemed handoff codes are invalidated immediately');
assert.match(tokenAuth, /assertDesktopJobAccess/, 'desktop API access can be restricted to the selected job');
assert.match(tokenAuth, /createHash\('sha256'\)/, 'desktop access tokens must be stored as hashes');
assert.doesNotMatch(desktopIntegration, /Copy this connection token|Connect device|clipboard/, 'settings must not ask users to copy connection codes');
assert.match(desktopIntegration, /No codes, passwords or device connection setup required/, 'settings explains automatic handoff');
assert.match(automationJobService, /typeOfWorkKey:\s*typeOfWorkKey\(project\.projectType\)/, 'v2 snapshots carry a stable type-of-work key');
assert.match(automationJobService, /typeOfWorkKey\(warrant\?\.presetKey \?\? project\.projectType\)/, 'Building Warrant snapshots prefer the selected record preset');
assert.match(automationJobService, /const presetLabel = typeOfWorkLabel\(presetKey\)/, 'Building Warrant snapshots carry the selected preset label');
assert.match(desktopCallbackRoute, /idempotencyKey/, 'desktop callbacks require an idempotency key');
assert.match(desktopCallbackRoute, /AutomationJobEvent/, 'desktop callbacks are recorded in the audit event table');
assert.match(desktopCallbackRoute, /AWAITING_PORTAL_REVIEW/, 'desktop completion stops at explicit portal review');
assert.match(desktopCallbackRoute, /automation-job:\$\{id\}:retry/, 'retry deadlines use a stable source key');
assert.match(lifecycleService, /assertAutomationJobTransition/, 'job transitions are enforced through one lifecycle service');

console.log('desktop handoff security tests passed');
