import assert from 'node:assert/strict';
import { Prisma } from '@prisma/client';
import { allocatePercentages, scheduleReconciles, moneyDecimal, agreementTaxMatches } from '../src/lib/fees/agreement';
import { calculateProjectFinance, rankInvoiceSuggestions } from '../src/server/services/project-finance.service';
import { reconcileInvoiceCredits } from '../src/lib/xero/credits';
const d = (value: string | number) => new Prisma.Decimal(value);
assert.equal(agreementTaxMatches('STANDARD', '20.00', 20), true);
assert.equal(agreementTaxMatches('STANDARD', '20.00', 0), false);
assert.equal(agreementTaxMatches('ZERO', null, 0), true);
assert.equal(agreementTaxMatches('LEGACY_UNKNOWN', null, 0), false);
assert.equal(agreementTaxMatches('NOT_REGISTERED', null, undefined), false);
assert.deepEqual(allocatePercentages('100.01', [25, 50, 25]), ['25.00', '50.01', '25.00']);
assert.throws(() => moneyDecimal('1.001'));
assert.equal(scheduleReconciles('100', [{ amount: '100', enabled: true }]), true);
assert.equal(scheduleReconciles('100', [{ amount: '99', enabled: true }]), false);
const invoice = { xeroInvoiceId: 'invoice', invoiceType: 'ACCREC', status: 'AUTHORISED', currency: 'GBP', subtotal: d(100), total: d(120), amountPaid: d(30), amountDue: d(66), amountCredited: d(24), netCredited: d(20), dueDate: new Date('2026-10-08T00:00:00Z') };
const agreement = { agreedAmount: d(100), currency: 'GBP', vatTreatment: 'STANDARD' };
const totals = calculateProjectFinance([invoice, { ...invoice, xeroInvoiceId: 'draft', status: 'DRAFT' }, { ...invoice, xeroInvoiceId: 'void', status: 'VOIDED' }, { ...invoice, xeroInvoiceId: 'foreign', currency: 'EUR' }], agreement, new Date('2026-10-09T01:00:00Z'));
assert.equal(totals.get('GBP')!.paid.toFixed(2), '30.00');
assert.equal(totals.get('GBP')!.netInvoiced!.toFixed(2), '80.00');
assert.equal(totals.get('GBP')!.remaining!.toFixed(2), '20.00');
assert.equal(totals.get('GBP')!.outstanding.toFixed(2), '66.00');
assert.equal(totals.get('GBP')!.overdue.toFixed(2), '66.00');
assert.equal(totals.get('EUR')!.remaining, null);
assert.equal(calculateProjectFinance([{ ...invoice, netCredited: null }], agreement).get('GBP')!.remaining, null);
assert.equal(calculateProjectFinance([invoice], { ...agreement, agreedAmount: d(50) }).get('GBP')!.remaining!.toFixed(2), '-30.00');
assert.equal(calculateProjectFinance([invoice], { ...agreement, vatTreatment: 'LEGACY_UNKNOWN' }).get('GBP')!.remaining, null);
assert.equal(calculateProjectFinance([{ ...invoice, dueDate: new Date('2026-10-09T00:00:00Z') }], agreement, new Date('2026-10-08T23:30:00Z')).get('GBP')!.overdue.toFixed(2), '0.00');
const note = { status: 'AUTHORISED', currency: 'GBP', subtotal: d(20), totalTax: d(4), total: d(24), allocations: [{ invoiceId: 'invoice', amount: '24.00' }] };
assert.equal(reconcileInvoiceCredits('invoice', 'GBP', d(24), [note])!.toFixed(2), '20.00');
assert.equal(reconcileInvoiceCredits('invoice', 'GBP', d(12), [{ ...note, allocations: [{ invoiceId: 'invoice', amount: '12.00' }] }]), null);
assert.equal(reconcileInvoiceCredits('invoice', 'GBP', d(24), [{ ...note, status: 'VOIDED' }]), null);
const suggestions = rankInvoiceSuggestions([{ ...invoice, reference: 'AP-123', xeroContactId: 'client' }, { ...invoice, xeroInvoiceId: 'ambiguous', reference: 'AP-12', xeroContactId: 'other' }], { projectReference: 'AP-123', clientContactId: 'client', milestoneIds: [] });
assert.equal(suggestions[0].score, 120); assert.equal(suggestions[1].score, 0);
console.log('Workflow finance: penny allocation, cash/credits, unknown net, London dates, currencies and explicit matching passed.');
