import assert from 'node:assert/strict';
import { randomUUID, createHash } from 'node:crypto';
import { prisma } from '../src/lib/db/prisma';
import { createApplicationDraftUploadIntent, finaliseApplicationDraftDocument, removeApplicationDraftDocument } from '../src/server/services/application-draft-files.service';
import { claimProcessingJob, fencedProcessingWrite, enqueueProjectDocumentProcessing, runDocumentProcessingWorker } from '../src/server/services/document-processing.service';
import { applicationDraftResponse } from '../src/server/services/application-draft-view.service';
import { assignProjectFeePlan } from '../src/server/services/fee-plans.service';
import { projectFeePlanSchema } from '../src/lib/validation/fee-plans';
import { getApplicationDraftForOrganisation } from '../src/server/services/application-draft.service';
import { databaseTable } from '../src/lib/db/table';
import { reserveProjectUpload, finaliseProjectUpload } from '../src/server/services/project-upload.service';

const configuredSchema = new URL(process.env.DATABASE_URL!).searchParams.get('schema');
assert.equal(configuredSchema, 'workflow_overhaul_preview_20261009', 'integration tests must use the isolated schema');
const [{ schema }] = await prisma.$queryRaw<Array<{ schema: string }>>`SELECT table_schema AS schema FROM information_schema.tables WHERE table_schema = ${configuredSchema} AND table_name = 'DocumentProcessingJob'`;
assert.equal(schema, configuredSchema, 'the isolated processing table must exist');
assert.ok(databaseTable('DocumentProcessingJob').sql.includes(configuredSchema), 'raw locks explicitly name the isolated schema rather than relying on pooler search_path');
const suffix = randomUUID();
const organisation = await prisma.organisation.create({ data: { name: 'Workflow database fixtures', slug: `workflow-db-${suffix}` } });
const user = await prisma.user.create({ data: { name: 'Workflow database tester', email: `workflow-db-${suffix}@example.test`, passwordHash: 'test-only-no-login' } });
const draft = await prisma.applicationDraft.create({ data: { organisationId: organisation.id, createdById: user.id, expiresAt: new Date(Date.now() + 86_400_000), selectedApplicationType: 'HOUSEHOLDER_PLANNING' } });
const bytes = Buffer.from('%PDF-1.4\nSynthetic isolated integration fixture\n%%EOF');
const hash = createHash('sha256').update(bytes).digest('hex');
// Three simultaneous reservations with the same idempotency identity must
// converge despite serializable transaction conflicts.
const repeated = await Promise.all(Array.from({ length: 3 }, () => createApplicationDraftUploadIntent(draft.id, organisation.id, { filename: 'same.pdf', mimeType: 'application/pdf', size: bytes.length, clientSha256: hash })));
assert.equal(new Set(repeated.map(result => result.document.id)).size, 1);
for (let offset = 0; offset < 19; offset += 3) await Promise.all(Array.from({ length: Math.min(3, 19 - offset) }, (_, index) => createApplicationDraftUploadIntent(draft.id, organisation.id, { filename: `fixture-${offset + index}.pdf`, mimeType: 'application/pdf', size: bytes.length, clientSha256: hash })));
assert.equal(await prisma.applicationDraftDocument.count({ where: { draftId: draft.id } }), 20);
await assert.rejects(() => createApplicationDraftUploadIntent(draft.id, organisation.id, { filename: 'over-limit.pdf', mimeType: 'application/pdf', size: bytes.length, clientSha256: hash }), /20 files/);
const target = repeated[0];
const put = await fetch(target.signedUpload!.uploadUrl, { method: 'PUT', body: bytes, headers: { 'content-type': 'application/pdf' } }); assert.equal(put.ok, true);
const first = await finaliseApplicationDraftDocument(draft.id, target.document.id, organisation.id);
const second = await finaliseApplicationDraftDocument(draft.id, target.document.id, organisation.id);
assert.equal(first.id, second.id); assert.equal(first.sha256, hash);
await removeApplicationDraftDocument(draft.id, target.document.id, organisation.id);
await assert.rejects(() => finaliseApplicationDraftDocument(draft.id, target.document.id, organisation.id), /not found|cancelled/);
assert.ok((await prisma.applicationDraftDocument.findUniqueOrThrow({ where: { id: target.document.id } })).cancelledAt);
const persistedDraft = await prisma.applicationDraft.findUniqueOrThrow({ where: { id: draft.id }, include: { documents: true } });
assert.equal(applicationDraftResponse(persistedDraft).documents.length, 19, 'cancelled tombstones stay out of the refreshed review');
await assert.rejects(() => createApplicationDraftUploadIntent(draft.id, organisation.id, { filename: 'same.pdf', mimeType: 'application/pdf', size: bytes.length, clientSha256: hash }), /cancelled/);
const reselected = await createApplicationDraftUploadIntent(draft.id, organisation.id, { filename: 'same.pdf', mimeType: 'application/pdf', size: bytes.length, clientSha256: hash, clientUploadId: randomUUID() });
assert.notEqual(reselected.document.id, target.document.id, 'a deliberate reselection gets a new attempt without reviving the cancelled identity');
await removeApplicationDraftDocument(draft.id, reselected.document.id, organisation.id);
await assert.rejects(() => getApplicationDraftForOrganisation(draft.id, 'another-organisation'), /not found/);
// Claims serialize on the organisation; only two live leases are issued.
for (let index = 0; index < 3; index++) await prisma.documentProcessingJob.create({ data: { organisationId: organisation.id, idempotencyKey: `lease-${suffix}-${index}`, processingVersion: 'fixture' } });
const claims = await Promise.all(['worker-a','worker-b','worker-c'].map(owner => claimProcessingJob(owner, organisation.id)));
assert.equal(claims.filter(Boolean).length, 2);
const expired = claims.find(Boolean)!;
await prisma.documentProcessingJob.update({ where: { id: expired.id }, data: { leaseExpiresAt: new Date(0) } });
const replacement = await claimProcessingJob('replacement', organisation.id); assert.equal(replacement!.id, expired.id);
let writes = 0;
assert.equal(await fencedProcessingWrite(expired, async () => { writes++; }), false);
assert.equal(await fencedProcessingWrite(replacement!, async () => { writes++; }), true);
assert.equal(writes, 1);
const project = await prisma.project.create({ data: { organisationId: organisation.id, name: 'Historical fee fixture' } });
const projectInput = { filename: 'cancelled-project.pdf', mimeType: 'application/pdf', size: bytes.length, clientSha256: hash, clientUploadId: randomUUID() };
const projectIntent = await reserveProjectUpload(organisation.id, user.id, project.id, projectInput);
const sameContent = await reserveProjectUpload(organisation.id, user.id, project.id, { ...projectInput, clientUploadId: randomUUID() });
assert.equal(sameContent.document.id, projectIntent.document.id, 'active matching content is reused across reselection');
await prisma.projectUploadIntent.update({ where: { id: projectIntent.document.id }, data: { cancelledAt: new Date(), status: 'CANCELLED' } });
await assert.rejects(() => reserveProjectUpload(organisation.id, user.id, project.id, projectInput), /cancelled/);
const projectReselected = await reserveProjectUpload(organisation.id, user.id, project.id, { ...projectInput, clientUploadId: randomUUID() });
assert.notEqual(projectReselected.document.id, projectIntent.document.id);
await assert.rejects(() => finaliseProjectUpload(organisation.id, project.id, projectIntent.document.id), /not found/);
const failedDocument = await prisma.projectDocument.create({ data: { organisationId: organisation.id, projectId: project.id, uploadedById: user.id, fileName: 'retry.pdf', originalName: 'retry.pdf', storageUrl: '', storageKey: target.document.storageKey, mimeType: 'application/pdf', sizeBytes: bytes.length, fileHash: hash, analysisStatus: 'FAILED', sortSource: 'MANUAL', type: 'LOCATION_PLAN' } });
const processing = await enqueueProjectDocumentProcessing(failedDocument.id, organisation.id);
await prisma.documentProcessingJob.update({ where: { id: processing!.id }, data: { state: 'FAILED', attempts: 5 } });
const retries = await Promise.all([1, 2].map(() => enqueueProjectDocumentProcessing(failedDocument.id, organisation.id, { retry: true })));
assert.equal(new Set(retries.map(job => job!.id)).size, 1);
assert.equal(retries[0]!.state, 'WAITING'); assert.equal(retries[0]!.attempts, 0);
assert.equal((await prisma.projectDocument.findUniqueOrThrow({ where: { id: failedDocument.id } })).type, 'LOCATION_PLAN', 'explicit retry preserves manual classification');
await prisma.documentProcessingJob.updateMany({ where: { organisationId: organisation.id, id: { not: processing!.id } }, data: { state: 'CANCELLED', leaseOwner: null, leaseExpiresAt: null } });
assert.equal((await fetch(target.signedUpload!.uploadUrl, { method: 'PUT', body: bytes, headers: { 'content-type': 'application/pdf' } })).ok, true);
await runDocumentProcessingWorker(organisation.id);
const classified = await prisma.projectDocument.findUniqueOrThrow({ where: { id: failedDocument.id } });
assert.equal(classified.type, 'LOCATION_PLAN'); assert.equal(classified.sortSource, 'MANUAL');
assert.ok(classified.analysisStatus && !['PENDING', 'FAILED'].includes(classified.analysisStatus), 'manual classification retains fresh analysis metadata after retry');
assert.ok(classified.analysisResult);
assert.ok(classified.analysedAt);
assert.equal((await enqueueProjectDocumentProcessing(failedDocument.id, organisation.id, { retry: true }))!.state, 'SUCCEEDED', 'retry cannot reset successful work');
await assert.rejects(() => enqueueProjectDocumentProcessing(failedDocument.id, 'another-organisation', { retry: true }), /not found/);
const assign = (input: unknown) => prisma.$transaction(tx => assignProjectFeePlan(tx, organisation.id, project.id, user.id, projectFeePlanSchema.parse(input)));
const legacy = await assign({ name: 'Historical milestone plan', milestones: [{ milestoneKey: 'historic', label: 'Historic fee', triggerEventType: null, amount: '100.01', invoiceDescription: 'Historic fee' }] });
assert.equal(legacy.agreedAmount, null); assert.equal(legacy.vatTreatment, 'LEGACY_UNKNOWN');
const agreement = await assign({ agreedAmount: '100.01', vatTreatment: 'ZERO', revision: legacy.revision });
assert.equal(agreement.milestones[0].id, legacy.milestones[0].id);
await assert.rejects(() => assign({ agreedAmount: '90.00', vatTreatment: 'ZERO', revision: legacy.revision }), /another session/);
const percent = await assign({ agreedAmount: '100.01', vatTreatment: 'ZERO', revision: agreement.revision, milestones: [25,50,25].map((percentage, index) => ({ milestoneKey: `percent-${index}`, label: 'Stage', triggerEventType: null, amount: '0.01', percentage, invoiceDescription: 'Stage' })) });
assert.deepEqual(percent.milestones.filter(row => row.enabled).map(row => row.amount.toFixed(2)), ['25.00','50.01','25.00']);
await prisma.projectFeeMilestone.update({ where: { id: percent.milestones.find(row => row.enabled)!.id }, data: { enabled: false, state: 'WAIVED' } });
assert.equal((await prisma.projectFeePlan.findUniqueOrThrow({ where: { id: percent.id } })).agreedAmount!.toFixed(2), '100.01');
assert.equal(await prisma.projectFeeRevision.count({ where: { projectFeePlanId: legacy.id } }), 3);
// Revision comparisons are exercised through the real review service below
// using a prepared draft generated by the authenticated browser fixture.
await prisma.$disconnect();
console.log('Isolated database: 20-file concurrent reservations, idempotent verification, tombstones, org isolation, two leases, expired-owner fencing, idempotent analysis retry, manual classification and historical fee revisions passed.');
