ALTER TYPE "LifecycleAggregateType" ADD VALUE 'PLANNING_APPLICATION';
ALTER TYPE "LifecycleAggregateType" ADD VALUE 'BUILDING_WARRANT_APPLICATION';

ALTER TYPE "LifecycleEventType" ADD VALUE 'DOCUMENT_REVIEW_COMPLETED';
ALTER TYPE "LifecycleEventType" ADD VALUE 'PLANNING_READY';
ALTER TYPE "LifecycleEventType" ADD VALUE 'PLANNING_READINESS_REVOKED';
ALTER TYPE "LifecycleEventType" ADD VALUE 'PLANNING_SUBMITTED';
ALTER TYPE "LifecycleEventType" ADD VALUE 'PLANNING_APPROVED';
ALTER TYPE "LifecycleEventType" ADD VALUE 'BUILDING_WARRANT_READY';
ALTER TYPE "LifecycleEventType" ADD VALUE 'BUILDING_WARRANT_READINESS_REVOKED';

ALTER TYPE "LifecycleEventSource" ADD VALUE 'APPLICATION_PREFLIGHT';
ALTER TYPE "LifecycleEventSource" ADD VALUE 'APPLICATION_STATUS';

ALTER TYPE "ActionItemKind" ADD VALUE 'PLANNING_PREPARATION';
ALTER TYPE "ActionItemKind" ADD VALUE 'PLANNING_FINAL_REVIEW';
ALTER TYPE "ActionItemKind" ADD VALUE 'BUILDING_WARRANT_ACTION';
ALTER TYPE "ActionItemKind" ADD VALUE 'BUILDING_WARRANT_FINAL_REVIEW';

ALTER TYPE "ProjectActivityEventType" ADD VALUE 'DOCUMENT_REVIEW_COMPLETED';
ALTER TYPE "ProjectActivityEventType" ADD VALUE 'PLANNING_READY';
ALTER TYPE "ProjectActivityEventType" ADD VALUE 'PLANNING_SUBMITTED';
ALTER TYPE "ProjectActivityEventType" ADD VALUE 'PLANNING_APPROVED';
ALTER TYPE "ProjectActivityEventType" ADD VALUE 'BUILDING_WARRANT_READY';
ALTER TYPE "ProjectActivityEventType" ADD VALUE 'WORKFLOW_DEADLINE_OVERRIDDEN';

ALTER TYPE "WorkflowTargetKey" ADD VALUE 'PLANNING_PREPARATION';
ALTER TYPE "WorkflowTargetKey" ADD VALUE 'PLANNING_FINAL_REVIEW';
ALTER TYPE "WorkflowTargetKey" ADD VALUE 'BUILDING_WARRANT_ACTION';
ALTER TYPE "WorkflowTargetKey" ADD VALUE 'BUILDING_WARRANT_FINAL_REVIEW';

CREATE TYPE "DeadlineManagedBy" AS ENUM ('MANUAL', 'WORKFLOW', 'GMAIL', 'PORTAL');

ALTER TABLE "ProjectActivity" ALTER COLUMN "sourceLifecycleEventId" DROP NOT NULL;

ALTER TABLE "Deadline"
  ADD COLUMN "managedBy" "DeadlineManagedBy" NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN "calculatedDueDate" TIMESTAMP(3),
  ADD COLUMN "manualOverrideAt" TIMESTAMP(3),
  ADD COLUMN "manualOverrideById" TEXT;

CREATE INDEX "Deadline_manualOverrideById_idx" ON "Deadline"("manualOverrideById");

ALTER TABLE "Deadline"
  ADD CONSTRAINT "Deadline_manualOverrideById_fkey"
  FOREIGN KEY ("manualOverrideById") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;
