export const TYPE_OF_WORK_OPTIONS = [
  'Domestic',
  'Commercial',
  'Extension',
  'Alteration',
  'New Build',
  'Conversion',
  'Change of Use',
  'Loft Conversion',
  'Garage Conversion',
  'Planning Application',
  'Building Warrant',
  'Householder Application',
  'Certificate of Lawfulness',
  'Listed Building Consent',
  'Conservation Area Consent',
  'Demolition',
  'Other',
] as const;
