ALTER TYPE "LifecycleEventType" ADD VALUE IF NOT EXISTS 'PLANNING_REFUSED';
ALTER TYPE "LifecycleEventType" ADD VALUE IF NOT EXISTS 'BUILDING_WARRANT_GRANTED';

ALTER TYPE "ProjectActivityEventType" ADD VALUE IF NOT EXISTS 'PLANNING_REFUSED';
ALTER TYPE "ProjectActivityEventType" ADD VALUE IF NOT EXISTS 'BUILDING_WARRANT_GRANTED';
